### PR TITLE
Rename "profiles" to "build-configs"

### PR DESCRIPTION
**Pull request by joverlee521**
## Description of proposed changes

Rename "profiles" to ~"customizations"~ "build-configs" to avoid confusion with [Snakemake's Profiles](https://snakemake.readthedocs.io/en/stable/executing/cli.html#profiles).

This allows us to also rename custom configs to `config.yaml` since it no longer clashes with Snakemake's Profile configs. 

## Related issue(s)

Motivated by feedback in https://github.com/nextstrain/pathogen-repo-template/pull/24

## Checklist

- [x] Checks pass

### CODE REVIEW

**Review by tsibley — APPROVED** [review]
This LGTM as a direction. I'm not sold on the exact term "customizations", but I don't have a better suggestion!

**Comment by joverlee521** [comment]
> I'm not sold on the exact term "customizations", but I don't have a better suggestion!

I'm not super happy about the term "customizations" either but I can't think of anything better. Definitely open to other people's suggestions 😄

**Comment by huddlej** [comment]
I think of the contents/meaning of those files/directories as defining "builds", since they include parameters and often other input files and custom commands required for the workflow. That name falls short of [our definition of "build"](https://docs.nextstrain.org/en/latest/reference/glossary.html#term-build), since these files don't include all of the commands. We do tend to call these files "builds", though, in [ncov](https://github.com/nextstrain/ncov/blob/master/nextstrain_profiles/nextstrain-open/builds.yaml).

I didn't like "customizations" initially, since it seems to downplay the critical nature of these files, but it's growing on me. It does seem to cover the combination of parameters plus _custom_ (🙃) files and rules.

**Comment by victorlin** [comment]
I'm also iffy on "customizations" and I think the reason is that it's typically used to represent something more specific. I'll try to explain below.

In comparing "configurations" vs. "customizations", both represent modifications of the software's default behavior. The difference lies in whether the modifications are formally supported features.

- "Configurations" are formally supported features (e.g. a command line option like `augur filter --min-date`).
- "Customizations" implies extension of the underlying software with new features (e.g. extension of workflow with new rules).

Ideally these would be classified separately, where most usage can be done with configurations alone, and only a few special cases need customization. The ncov workflow makes these concepts distinct: the **configuration** file supports additional **customizations** via [custom_rules](https://docs.nextstrain.org/projects/ncov/en/latest/reference/workflow-config-file.html#custom-rules).

Currently this repo structure doesn't define structure that deeply, and maybe it shouldn't. I also can't think of a better name. Just wanted to share thoughts about why "customizations" sounds weird here.

**Comment by tsibley** [comment]
@victorlin I think you've hit the nail on the head for why "customizations" isn't sitting easy with me.

**Comment by tsibley** [comment]
@huddlej [wrote](https://github.com/nextstrain/pathogen-repo-template/pull/27#issuecomment-1904526828):

> That name falls short of [our definition of "build"](https://docs.nextstrain.org/en/latest/reference/glossary.html#term-build), since these files don't include all of the commands.

Yeah, this is also part of why "customizations" doesn't feel right: generally if you're customizing something you have a single set of changes to tailor to your purposes. Here, we have many different sets of changes that seem to want/deserve their own proper noun and concept less abstract than "customizations" (or "configurations" for that matter). "Builds" would be in the running there…

**Comment by tsibley** [comment]
> …since these files don't include all of the commands.

…but they are colocated with the commands in the workflow. And in one sense the configs and input data determine the commands which the workflow will run. I think there'd be a decent case made for calling these "builds" or "build configurations".

**Comment by joverlee521** [comment]
Thanks for spelling out "configurations" vs "customizations" @victorlin! This made me think of video game mods, which encompasses both...How would people feel about "modifications" or "build_modifications"?

**Comment by victorlin** [comment]
"Modifications" makes more sense than "customizations", but isn't commonly used to describe "tailoring software to suit one's needs". I like the idea of centering on configurations (@tsibley's suggested "build configurations") that can optionally be extended with customizations - ncov already sets precedence for this.

However, "configurations" would be confusing with the existing `config` directory. I just caught up on discussions in #24, and if I'm understanding correctly, `config` is only used for defaults. In that case, I'd propose to rename `config` → `[configuration_]defaults` ([like ncov](https://github.com/nextstrain/ncov/tree/master/defaults)) and use `customizations` → `[build_]configurations` here.

**Comment by joverlee521** [comment]
> I like the idea of centering on configurations (@tsibley's suggested "build configurations") that can optionally be extended with customizations - ncov already sets precedence for this.

That's fair! 

> In that case, I'd propose to rename config → [configuration_]defaults ([like ncov](https://github.com/nextstrain/ncov/tree/master/defaults)) and use customizations → [build_]configurations here.

I'll go with `defaults` and `build_configs` to keep them short.

**Comment by tsibley** [comment]
(Maybe it's just me, but can we consistently use hyphens instead of underscores, e.g. `build-configs`? Pretty please?)

**Pull request merged**
